name: New Issues to Triage

on:
  issues:
    types: [ opened ]

jobs:
  new-issue-to-triage:
    runs-on: ubuntu-latest
    name: New Issue to Triage
    steps:
    - name: New issues to Service Triage
      uses: alex-page/github-project-automation-plus@v0.3.0
      if: "! (contains(github.event.issue.labels.*.name, 'Epic') || contains(github.event.issue.labels.*.name, 'kind/epic'))"
      with:
        project: Service Team
        column:  Triage ðŸ”€
        repo-token:  ${{ secrets.PULUMI_BOT_ACTIONS_ORG_ACCESS }} 
