name: Scheduled
on:
  schedule:
    # Daily at 3:00PM UTC
    - cron: 0 15 * * *
jobs:
  cleanup:
    name: Find and remove buckets
    runs-on: ubuntu-18.04
    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
          role-session-name: BucketCleanupSession

      - name: Find and remove buckets
        run: make ci-scheduled
        env:
            PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
