languageCode = "en-us"
title = "Pulumi - Modern Infrastructure as Code"

disableKinds = ["category", "taxonomyTerm"]
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsUseClasses = true

# We always generate the robots.txt file. But based on the environment
# built, it may disallow crawling.
enableRobotsTXT = true

[outputFormats.RSS]
    baseName = "rss"

# We set the outputs explicitly to just "HTML" as otherwise they default to both
# "HTML" and "RSS", and we only want to generate RSS for the blog section -- not
# all sections/taxonomies. We enable RSS as an output for the blog section alone
# in the front matter of content/blog/_index.md and have a custom RSS template
# in layouts/blog/rss.xml.
[outputs]
    home = ["HTML"]
    section = ["HTML"]
    taxonomy = ["HTML"]

[taxonomies]
    author = "authors"
    tag = "tags"

[permalinks]
    authors = "/blog/author/:slug/"
    tags = "/blog/tag/:slug/"

[blackfriday]
    fractions = false

[params]
    canonicalURL = "https://www.pulumi.com"
    repositoryURL = "https://github.com/pulumi/docs"
    repositoryBranch = "master"
    summary = "Pulumi's open source infrastructure as code SDK enables you and your team to create, deploy, and manage infrastructure on any cloud, reliably and productively, using your favorite languages."
