# -------------------------------------
# Command Line Menu
# -------------------------------------
cli:
  - name: cancel
    url: /docs/cli/commands/pulumi_cancel/
    weight: 1
    parent: commands
    aliases:
      - /docs/cli/pulumi_cancel/

  - name: config
    url: /docs/cli/commands/pulumi_config/
    weight: 2
    parent: commands
    aliases:
      - /docs/cli/pulumi_config/

  - name: console
    url: /docs/cli/commands/pulumi_console/
    weight: 3
    parent: commands
    aliases:
      - /docs/cli/pulumi_console/

  - name: destroy
    url: /docs/cli/commands/pulumi_destroy/
    weight: 4
    parent: commands
    aliases:
      - /docs/cli/pulumi_destroy/

  - name: import
    url: /docs/cli/commands/pulumi_import/
    weight: 5
    parent: commands
    aliases:
      - /docs/cli/pulumi_import/

  - name: login
    url: /docs/cli/commands/pulumi_login/
    weight: 6
    parent: commands
    aliases:
      - /docs/cli/pulumi_login/

  - name: logout
    url: /docs/cli/commands/pulumi_logout/
    weight: 7
    parent: commands
    aliases:
      - /docs/cli/pulumi_logout/

  - name: logs
    url: /docs/cli/commands/pulumi_logs/
    weight: 8
    parent: commands
    aliases:
      - /docs/cli/pulumi_logs/

  - name: new
    url: /docs/cli/commands/pulumi_new/
    weight: 9
    parent: commands
    aliases:
      - /docs/cli/pulumi_new/

  - name: plugin
    url: /docs/cli/commands/pulumi_plugin/
    weight: 10
    parent: commands
    aliases:
      - /docs/cli/pulumi_plugin/

  - name: policy
    url: /docs/cli/commands/pulumi_policy/
    weight: 11
    parent: commands
    aliases:
      - /docs/cli/pulumi_policy/

  - name: preview
    url: /docs/cli/commands/pulumi_preview/
    weight: 12
    parent: commands
    aliases:
      - /docs/cli/pulumi_preview/

  - name: refresh
    url: /docs/cli/commands/pulumi_refresh/
    weight: 13
    parent: commands
    aliases:
      - /docs/cli/pulumi_refresh/

  - name: stack
    url: /docs/cli/commands/pulumi_stack/
    weight: 14
    parent: commands
    aliases:
      - /docs/cli/pulumi_stack/

  - name: state
    url: /docs/cli/commands/pulumi_state/
    weight: 15
    parent: commands
    aliases:
      - /docs/cli/pulumi_state/

  - name: up
    url: /docs/cli/commands/pulumi_up/
    weight: 16
    parent: commands
    aliases:
      - /docs/cli/pulumi_up/

  - name: version
    url: /docs/cli/commands/pulumi_version/
    weight: 17
    parent: commands
    aliases:
      - /docs/cli/pulumi_version/

  - name: whoami
    url: /docs/cli/commands/pulumi_whoami/
    weight: 18
    parent: commands
    aliases:
      - /docs/cli/pulumi_whoami/

  - name: Node.js
    parent: Pulumi SDK
    url: /docs/reference/pkg/nodejs/pulumi/pulumi
    weight: 1

  - name: Python
    parent: Pulumi SDK
    url: /docs/reference/pkg/python/pulumi
    weight: 2

  - name: Go
    parent: Pulumi SDK
    url: https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v3/go/pulumi
    weight: 3

  - name: .NET Core
    parent: Pulumi SDK
    url: /docs/reference/pkg/dotnet
    weight: 4

  - name: Java
    parent: Pulumi SDK
    url: /docs/reference/pkg/java/
    weight: 5

  - name: Pulumi YAML
    parent: Pulumi SDK
    url: /docs/reference/yaml/
    weight: 6
