# -------------------------------------
# Command Line Menu
# -------------------------------------
cli:
  - name: pulumi
    url: /docs/iac/cli-commands/pulumi/
    weight: 1
    parent: iac-cli-commands

  - name: about
    url: /docs/iac/cli-commands/pulumi_about/
    weight: 2
    parent: iac-cli-commands

  - name: cancel
    url: /docs/iac/cli-commands/pulumi_cancel/
    weight: 2
    parent: iac-cli-commands

  - name: config
    url: /docs/iac/cli-commands/pulumi_config/
    weight: 2
    parent: iac-cli-commands

  - name: console
    url: /docs/iac/cli-commands/pulumi_console/
    weight: 2
    parent: iac-cli-commands

  - name: convert
    url: /docs/iac/cli-commands/pulumi_convert/
    weight: 2
    parent: iac-cli-commands

  - name: destroy
    url: /docs/iac/cli-commands/pulumi_destroy/
    weight: 2
    parent: iac-cli-commands

  - name: env
    url: /docs/iac/cli-commands/pulumi_env/
    weight: 2
    parent: iac-cli-commands

  - name: gen-completion
    url: /docs/iac/cli-commands/pulumi_gen-completion/
    weight: 2
    parent: iac-cli-commands

  - name: import
    url: /docs/iac/cli-commands/pulumi_import/
    weight: 2
    parent: iac-cli-commands

  - name: login
    url: /docs/iac/cli-commands/pulumi_login/
    weight: 2
    parent: iac-cli-commands

  - name: logout
    url: /docs/iac/cli-commands/pulumi_logout/
    weight: 2
    parent: iac-cli-commands

  - name: logs
    url: /docs/iac/cli-commands/pulumi_logs/
    weight: 2
    parent: iac-cli-commands

  - name: new
    url: /docs/iac/cli-commands/pulumi_new/
    weight: 2
    parent: iac-cli-commands

  - name: org
    url: /docs/iac/cli-commands/pulumi_org/
    weight: 2
    parent: iac-cli-commands

  - name: package
    url: /docs/iac/cli-commands/pulumi_package/
    weight: 2
    parent: iac-cli-commands

  - name: plugin
    url: /docs/iac/cli-commands/pulumi_plugin/
    weight: 2
    parent: iac-cli-commands

  - name: policy
    url: /docs/iac/cli-commands/pulumi_policy/
    weight: 2
    parent: iac-cli-commands

  - name: preview
    url: /docs/iac/cli-commands/pulumi_preview/
    weight: 2
    parent: iac-cli-commands

  - name: refresh
    url: /docs/iac/cli-commands/pulumi_refresh/
    weight: 2
    parent: iac-cli-commands

  - name: schema
    url: /docs/iac/cli-commands/pulumi_schema/
    weight: 2
    parent: iac-cli-commands

  - name: stack
    url: /docs/iac/cli-commands/pulumi_stack/
    weight: 2
    parent: iac-cli-commands

  - name: state
    url: /docs/iac/cli-commands/pulumi_state/
    weight: 2
    parent: iac-cli-commands

  - name: up
    url: /docs/iac/cli-commands/pulumi_up/
    weight: 2
    parent: iac-cli-commands

  - name: version
    url: /docs/iac/cli-commands/pulumi_version/
    weight: 2
    parent: iac-cli-commands

  - name: watch
    url: /docs/iac/cli-commands/pulumi_watch/
    weight: 2
    parent: iac-cli-commands

  - name: whoami
    url: /docs/iac/cli-commands/pulumi_whoami/
    weight: 2
    parent: iac-cli-commands

# -------------------------------------
# ESC Command Line Menu
# -------------------------------------
esc:

  - name: esc
    url: /docs/esc/cli/commands/esc/
    weight: 1
    parent: esc-cli-commands

  - name: esc env
    url: /docs/esc/cli/commands/esc_env/
    weight: 2
    parent: esc-cli-commands

  - name: esc completion
    url: /docs/esc/cli/commands/esc_completion/
    weight: 2
    parent: esc-cli-commands

  - name: esc env edit
    url: /docs/esc/cli/commands/esc_env_edit/
    weight: 2
    parent: esc-cli-commands

  - name: esc env get
    url: /docs/esc/cli/commands/esc_env_get/
    weight: 2
    parent: esc-cli-commands

  - name: esc env init
    url: /docs/esc/cli/commands/esc_env_init/
    weight: 2
    parent: esc-cli-commands

  - name: esc env ls
    url: /docs/esc/cli/commands/esc_env_ls/
    weight: 2
    parent: esc-cli-commands

  - name: esc env rm
    url: /docs/esc/cli/commands/esc_env_rm/
    weight: 2
    parent: esc-cli-commands

  - name: esc env set
    url: /docs/esc/cli/commands/esc_env_set/
    weight: 2
    parent: esc-cli-commands

  - name: esc login
    url: /docs/esc/cli/commands/esc_login/
    weight: 2
    parent: esc-cli-commands

  - name: esc open
    url: /docs/esc/cli/commands/esc_open/
    weight: 2
    parent: esc-cli-commands

  - name: esc run
    url: /docs/esc/cli/commands/esc_run/
    weight: 2
    parent: esc-cli-commands

  - name: esc version
    url: /docs/esc/cli/commands/esc_version/
    weight: 2
    parent: esc-cli-commands


# -------------------------------------
# ESC SDKs Menu
# -------------------------------------

esc:
  - name: SDK docs
    parent: esc-typescript-sdk
    url: /docs/reference/pkg/nodejs/pulumi/esc-sdk/
    weight: 1
    identifier: esc-typescript-sdk-docs
  - name: SDK docs
    parent: esc-python-sdk
    url: /docs/reference/pkg/python/pulumi_esc_sdk/
    weight: 1
    identifier: esc-python-sdk-docs
  - name: SDK docs
    parent: esc-go-sdk
    url: https://pkg.go.dev/github.com/pulumi/esc-sdk/sdk/go
    weight: 1
    identifier: esc-go-sdk-docs

# -------------------------------------
# IaC Languages & SDKs Menus
# -------------------------------------

iac:
  - name: SDK docs
    parent: iac-languages-javascript
    url: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/
    weight: 1
    identifier: iac-languages-javascript-sdk
  - name: SDK docs
    parent: iac-languages-python
    url: https://www.pulumi.com/docs/reference/pkg/python/pulumi/
    weight: 1
    identifier: iac-languages-python-sdk
  - name: SDK docs
    parent: iac-languages-go
    url: https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v3/go/pulumi
    weight: 1
    identifier: iac-languages-go-sdk
  - name: SDK docs
    parent: iac-languages-dotnet
    url: https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.html
    weight: 1
    identifier: iac-languages-dotnet-sdk
  - name: SDK docs
    parent: iac-languages-java
    url: https://www.pulumi.com/docs/reference/pkg/java/
    weight: 1
    identifier: iac-languages-java-sdk
