baseURL = "https://pulumi.io/"
languageCode = "en-us"
title = "Pulumi"

disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS"]

pygmentsCodefences = true
pygmentsUseClasses = true

sectionPagesMenu = "main"

[blackfriday]
    fractions = false

[params]
    repositoryURL = "https://github.com/pulumi/docs"
    repositoryBranch = "master"


# Command Line Menu

[[menu.reference]]
    name = "Cancel"
    parent = "cli"
    url = "/reference/cli/pulumi_cancel/"
    weight = 1

[[menu.reference]]
    name = "Config"
    parent = "cli"
    url = "/reference/cli/pulumi_config/"
    weight = 2

[[menu.reference]]
    name = "Destroy"
    parent = "cli"
    url = "/reference/cli/pulumi_destroy/"
    weight = 3

[[menu.reference]]
    name = "Login"
    parent = "cli"
    url = "/reference/cli/pulumi_login/"
    weight = 4

[[menu.reference]]
    name = "Logout"
    parent = "cli"
    url = "/reference/cli/pulumi_logout/"
    weight = 5

[[menu.reference]]
    name = "Logs"
    parent = "cli"
    url = "/reference/cli/pulumi_logs/"
    weight = 5

[[menu.reference]]
    name = "New"
    parent = "cli"
    url = "/reference/cli/pulumi_new/"
    weight = 6

[[menu.reference]]
    name = "Plugin"
    parent = "cli"
    url = "/reference/cli/pulumi_plugin/"
    weight = 7

[[menu.reference]]
    name = "Preview"
    parent = "cli"
    url = "/reference/cli/pulumi_preview/"
    weight = 8

[[menu.reference]]
    name = "Refresh"
    parent = "cli"
    url = "/reference/cli/pulumi_refresh/"
    weight = 9

[[menu.reference]]
    name = "Stack"
    parent = "cli"
    url = "/reference/cli/pulumi_stack/"
    weight = 10

[[menu.reference]]
    name = "State"
    parent = "cli"
    url = "/reference/cli/pulumi_state/"
    weight = 11

[[menu.reference]]
    name = "Update"
    parent = "cli"
    url = "/reference/cli/pulumi_up/"
    weight = 11

[[menu.reference]]
    name = "Cancel"
    parent = "cli"
    url = "/reference/cli/pulumi_cancel/"
    weight = 1


# API Reference Menu

[[menu.reference]]
    parent = "node"
    identifier = "node-pulumi"
    name = "pulumi"
    url = "/reference/pkg/nodejs/pulumi/pulumi/"
    weight = 1

[[menu.reference]]
    parent = "node"
    name = "aws"
    url = "/reference/pkg/nodejs/pulumi/aws/"

[[menu.reference]]
    parent = "node"
    name = "awsx"
    url = "/reference/pkg/nodejs/pulumi/awsx/"

[[menu.reference]]
    parent = "node"
    name = "azure"
    url = "/reference/pkg/nodejs/pulumi/azure/"

[[menu.reference]]
    parent = "node"
    name = "azuread"
    url = "/reference/pkg/nodejs/pulumi/azuread/"

[[menu.reference]]
    parent = "node"
    name = "cloud"
    url = "/reference/pkg/nodejs/pulumi/cloud/"

# Note: We deliberately aren't including the @pulumi/cloud-aws and @pulumi/cloud-azure
# packages in the docs listing as they are implementation details of @pulumi/cloud.

[[menu.reference]]
    parent = "node"
    name = "cloudflare"
    url = "/reference/pkg/nodejs/pulumi/cloudflare/"

[[menu.reference]]
    parent = "node"
    name = "digitalocean"
    url = "/reference/pkg/nodejs/pulumi/digitalocean/"

[[menu.reference]]
    parent = "node"
    name = "docker"
    url = "/reference/pkg/nodejs/pulumi/docker/"

[[menu.reference]]
    parent = "node"
    name = "eks"
    url = "/reference/pkg/nodejs/pulumi/eks/"

[[menu.reference]]
    parent = "node"
    name = "f5bigip"
    url = "/reference/pkg/nodejs/pulumi/f5bigip/"

[[menu.reference]]
    parent = "node"
    name = "gcp"
    url = "/reference/pkg/nodejs/pulumi/gcp/"

[[menu.reference]]
    parent = "node"
    name = "kubernetes"
    url = "/reference/pkg/nodejs/pulumi/kubernetes/"

[[menu.reference]]
    parent = "node"
    name = "linode"
    url = "/reference/pkg/nodejs/pulumi/linode/"

[[menu.reference]]
    parent = "node"
    name = "mysql"
    url = "/reference/pkg/nodejs/pulumi/mysql/"

[[menu.reference]]
    parent = "node"
    name = "newrelic"
    url = "/reference/pkg/nodejs/pulumi/newrelic/"

[[menu.reference]]
    parent = "node"
    name = "openstack"
    url = "/reference/pkg/nodejs/pulumi/openstack/"

[[menu.reference]]
    parent = "node"
    name = "packet"
    url = "/reference/pkg/nodejs/pulumi/packet/"

[[menu.reference]]
    parent = "node"
    name = "random"
    url = "/reference/pkg/nodejs/pulumi/random/"

[[menu.reference]]
    parent = "node"
    name = "vsphere"
    url = "/reference/pkg/nodejs/pulumi/vsphere/"

[[menu.reference]]
    parent = "python"
    identifier = "python-pulumi"
    name = "pulumi"
    url = "/reference/pkg/python/pulumi/"
    weight = 1

[[menu.reference]]
    parent = "python"
    name = "pulumi_aws"
    url = "/reference/pkg/python/pulumi_aws/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_azure"
    url = "/reference/pkg/python/pulumi_azure/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_azuread"
    url = "/reference/pkg/python/pulumi_azuread/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_cloudflare"
    url = "/reference/pkg/python/pulumi_cloudflare/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_digitalocean"
    url = "/reference/pkg/python/pulumi_digitalocean/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_f5bigip"
    url = "/reference/pkg/python/pulumi_f5bigip/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_gcp"
    url = "/reference/pkg/python/pulumi_gcp/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_kubernetes"
    url = "/reference/pkg/python/pulumi_kubernetes/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_linode"
    url = "/reference/pkg/python/pulumi_linode/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_newrelic"
    url = "/reference/pkg/python/pulumi_newrelic/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_openstack"
    url = "/reference/pkg/python/pulumi_openstack/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_random"
    url = "/reference/pkg/python/pulumi_random/"

[[menu.reference]]
    parent = "python"
    name = "pulumi_vsphere"
    url = "/reference/pkg/python/pulumi_vsphere/"
