name: Build and deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buildSite:
    env:
      GOPATH: ${{ github.workspace }}/go
    name: Install deps and build site
    runs-on: self-hosted
    permissions: {}
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Yarn
        run: npm install -g yarn

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Install assume-role
        run: go get -u github.com/remind101/assume-role

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Build and deploy
        run: make ci_${GITHUB_EVENT_NAME}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: browser-test-results
          path: cypress/videos

      - name: Archive bucket metadata
        uses: actions/upload-artifact@v2
        with:
          name: origin-bucket-metadata
          path: origin-bucket-metadata.json
