permissions: write-all # Equivalent to default permissions + id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: github-secrets/pulumi-docs
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN

name: customer-managed-workflow-agent cli docs build
on:
  repository_dispatch:
    types:
      - customer-managed-workflow-agent
jobs:
  pull-request:
    runs-on: ubuntu-latest
    needs: build-customer-managed-workflow-agent-cli-docs
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: checkout docs repo
        uses: actions/checkout@v6
      - name: set the customer-managed-workflow-agent version
        run: |
          echo "CMWA_VERSION=${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "customer-managed-workflow-agent/${{ github.run_id }}-${{ github.run_number }}"
          destination_branch: "master"
          pr_title: "Regen docs customer-managed-workflow-agent@${{ env.CMWA_VERSION }}"
          pr_body: "Automated PR"
          pr_label: "automation/customer-managed-workflow-agent-docs,automation/merge"
          github_token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
  build-customer-managed-workflow-agent-cli-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: set the customer-managed-workflow-agent version
        run: |
          echo "CMWA_VERSION=${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
      - name: checkout docs repo
        uses: actions/checkout@v6
        with:
          path: docs
      - name: Update latest version
        run: |
          VERSION_TAG=${{ env.CMWA_VERSION }}
          echo -n "${VERSION_TAG#v}" > ./static/customer-managed-workflow-agent/latest-version
        working-directory: docs
      - name: git status
        run: git status && git diff
        working-directory: docs
      - name: commit changes
        run: |
          git config --local user.email "bot@pulumi.com"
          git config --local user.name "pulumi-bot"
          git checkout -b customer-managed-workflow-agent/${{ github.run_id }}-${{ github.run_number }}
          git add static/
          git add content/
          git commit -m "Regenerating docs for customer-managed-workflow-agent@${{ env.CMWA_VERSION }}"
          git push origin customer-managed-workflow-agent/${{ github.run_id }}-${{ github.run_number }}
        working-directory: docs
    strategy:
      matrix:
        nodeversion:
          - "18.x"
  notify:
    if: failure()
    name: Send slack notification
    runs-on: ubuntu-latest
    needs: [pull-request, build-customer-managed-workflow-agent-cli-docs]
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Slack Notification
        uses: docker://sholung/action-slack-notify:v2.3.0
        env:
          SLACK_CHANNEL: docs-ops
          SLACK_COLOR: "#F54242"
          SLACK_MESSAGE: "customer-managed-workflow-agent cli docs build failure in pulumi/docs repo :meow_sad:"
          SLACK_USERNAME: docsbot
          SLACK_WEBHOOK: ${{ steps.esc-secrets.outputs.SLACK_WEBHOOK_URL }}
          SLACK_ICON: https://www.pulumi.com/logos/brand/avatar-on-white.png
