name: Pulumify
on: [pull_request, delete]
jobs:
  updateLivePreview:
    name: Update Live Preview
    runs-on: ubuntu-latest
    steps:
    - uses: docker://joeduffy/pulumify:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMIFY_BUILD: make ensure && hugo --buildFuture -e $GITHUB_SHA
        PULUMIFY_ROOT: public
        PULUMIFY_ORGANIZATION: pulumi
