env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

name: provider docs build
on:
  repository_dispatch:
    types:
      - tfgen-provider
jobs:
  pull-request:
    runs-on: ubuntu-latest
    needs: build-tfgen-provider-docs
    steps:
      - name: checkout docs repo
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.event.client_payload.project-shortname }}/${{ github.run_id }}-${{ github.run_number }}"
          destination_branch: "master"
          pr_title: "Regen docs ${{ github.event.client_payload.project-shortname }}@${{ github.event.client_payload.ref }}"
          pr_body: ""
          pr_label: "automation/tfgen-provider-docs"
          github_token: ${{ secrets.PULUMI_BOT_TOKEN }}

  build-tfgen-provider-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout docs repo
        uses: actions/checkout@v2
        with:
          path: docs
      - name: checkout pulumi repo
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi
          path: pulumi
      - name: checkout tfgen provider
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.ref }}
          path: ${{ github.event.client_payload.project }}
      - name: setup go
        uses: actions/setup-go@v2
      - name: setup node
        uses: actions/setup-node@v2-beta
      - name: setup python
        uses: actions/setup-python@v2
      - name: setup pipenv
        uses: dschep/install-pipenv-action@v1
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
      - run: make ensure ensure_tools
        working-directory: docs
      - name: run typedoc
        run: PKGS=${{ github.event.client_payload.project-shortname }} NOBUILD=true ./scripts/run_typedoc.sh
        working-directory: docs
      - name: generate resource docs
        run: ./scripts/gen_resource_docs.sh "${{ github.event.client_payload.project-shortname }}" true "${{ github.event.client_payload.ref }}"
        working-directory: docs
      - name: generate python docs
        run: ./scripts/generate_python_docs.sh "${{ github.event.client_payload.project-shortname }}"
        working-directory: docs
      - name: git status
        run: git status && git diff
        working-directory: docs
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          ref: "${{ github.event.client_payload.project-shortname }}/${{ github.run_id }}-${{ github.run_number }}"
          author_name: pulumi-bot
          author_email: "bot@pulumi.com"
          cwd: docs
